= Masters of Development

Masters of Development is a game developed with Python and Pygame.

== Installation

In order to run the game, install https://www.python.org/downloads/[Python 3.x] and https://www.pygame.org/wiki/GettingStarted[Pygame].

== Start

Start the game through calling `./masters_of_development.py`.

=== Arguments

==== width

Pass the desired screen width as first argument. Default is 1280.

==== height

Pass the desired screen height as second argument. Default is 720.

==== fullscreen

Pass as only or third argument `fullscreen` for fullscreen mode. Default is not fullscreen.

== The Game

=== Background Music

Switch the background music on/off through pressing `m`. Cycle through different music with `b` (previous) and `n` (next).

=== In game

Use Joysticks or keys `a` and `d` for player 1 or cursor keys `LEFT` and `RIGHT` for player 2 to move a player left or right.

Use Joystick button or Joystick up or key 'w' for player 1 or cursor key `UP`.

Press key `i` for some debug info.

== Misc

=== Font
* http://www.fontspace.com/codeman38/press-start-2p[Press Start 2P font]

=== Music
* https://freesound.org/people/NenadSimic/sounds/171185/
* https://freesound.org/people/dingo1/sounds/174589/
* https://freesound.org/people/sakebeats/sounds/176354/
* https://freesound.org/people/Mattc90/sounds/203532/
* https://freesound.org/people/rhodesmas/sounds/321388/
* https://freesound.org/people/sirplus/sounds/385822/
* https://freesound.org/people/orginaljun/sounds/396960/
* https://freesound.org/people/goredon/sounds/424285/
* https://freesound.org/people/jalastram/sounds/432776/

=== Sounds
* http://www.flashkit.com/soundfx/People/Talking/Player_o-NEOKOLOR-7551/index.php
* http://www.flashkit.com/soundfx/People/Talking/Player_t-Neokolor-7552/index.php
* https://freesound.org/people/tim.kahn/sounds/82986/
